CREATE DATABASE SP_Medical_Group
GO
USE SP_Medical_Group
GO

CREATE TABLE TipoUsuario(
IdTipoUsuario INT PRIMARY KEY IDENTITY ,
Titulo VARCHAR (200) NOT NULL UNIQUE
);
GO

CREATE TABLE Situacao(
IdSituacao INT PRIMARY KEY IDENTITY,
Situacao VARCHAR (200) NOT NULL
);
GO

CREATE TABLE Especialidade(
IdEspecialidade INT PRIMARY KEY IDENTITY,
TipoEspecialidade VARCHAR (200) NOT NULL
);
GO

CREATE TABLE Clinica(
IdClinica INT PRIMARY KEY IDENTITY,
RazaoSocial VARCHAR (200) NOT NULL,
NomeClinica VARCHAR (200) NOT NULL,
CNPJ VARCHAR (100) NOT NULL UNIQUE,
Endereco VARCHAR (200) NOT NULL UNIQUE,
Telefone VARCHAR (100) NOT NULL
);
GO

CREATE TABLE Usuario(
IdUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR (200) NOT NULL UNIQUE,
Senha  VARCHAR (200) NOT NULL,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);
GO

CREATE TABLE Paciente(
IdPaciente INT PRIMARY KEY IDENTITY,
NomePaciente VARCHAR (200)NOT NULL,
RG VARCHAR (100) NOT NULL UNIQUE,
Endereco VARCHAR (200) NOT NULL,
Telefone VARCHAR (100) NOT NULL,
Enfermidade VARCHAR (200) NOT NULL,
DataNascimento Date  NOT NULL,
IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO

CREATE TABLE Medico(
IdMedico INT PRIMARY KEY IDENTITY,
NomeMedico VARCHAR (200) NOT NULL,
CRM VARCHAR (100) NOT NULL UNIQUE,
IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade (IdEspecialidade),
IdClinica INT FOREIGN KEY REFERENCES Clinica (IdClinica)
);
GO

CREATE TABLE Consulta(
IdConsulta INT PRIMARY KEY IDENTITY,
DataConsulta DATETIME2 NOT NULL,
IdMedico INT FOREIGN KEY REFERENCES Medico (IdMedico),
IdPaciente INT FOREIGN KEY REFERENCES Paciente (IdPaciente),
IdSituacao INT FOREIGN KEY REFERENCES Situacao (IdSituacao),
);
GO

DROP DATABASE SP_Medical_Group